<?php

declare(strict_types=1);

namespace Helioviewer\EventsApi\Api\Controllers;

use Psr\Http\Message\ResponseInterface as Response;
use Psr\Http\Message\ServerRequestInterface as Request;

/**
 * Serves the pre-built failure report at /api/v1/failures and the HTML
 * browser at /failures. The report itself is generated by
 * bin/build-failure-report.php (run every 2h via scheduler.php).
 */
class FailuresController extends Controller
{
    private const REPORT_PATH = '/u/apps/data/failures-report.json';

    /**
     * Serve the HTML browser at /failures.
     */
    public function page(Request $request, Response $response): Response
    {
        $htmlPath = __DIR__ . '/../../../public/failures.html';
        if (!file_exists($htmlPath)) {
            return $this->error($response, 'Failures page not found', 404);
        }
        $response->getBody()->write(file_get_contents($htmlPath));
        return $response->withHeader('Content-Type', 'text/html');
    }

    /**
     * Serve the pre-built failure report JSON.
     * Client (failures.html) handles all filtering in-memory.
     */
    public function listJson(Request $request, Response $response): Response
    {
        if (!file_exists(self::REPORT_PATH)) {
            return $this->json($response, [
                'error'        => 'Report not yet built. Run `make build-failure-report` or wait for the scheduled rebuild.',
                'generated_at' => null,
                'total'        => 0,
                'items'        => [],
            ], 503);
        }

        $body = @file_get_contents(self::REPORT_PATH);
        if ($body === false) {
            return $this->error($response, 'Failed to read failures report');
        }

        $response->getBody()->write($body);
        return $response
            ->withHeader('Content-Type', 'application/json')
            ->withHeader('Cache-Control', 'no-cache');  // always revalidate; report itself is regenerated on a 2h cron
    }
}
